name: fitapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tillie.png
    - assets/cycling.png
    - assets/streak.png
    - assets/map.png
    - assets/more.png
    - assets/gear.png
    - assets/linh.png
    - assets/ivan.png
    - assets/arrow.png
    - assets/home.png
    - assets/hearticon.png
    - assets/award.png
    - assets/location.png
    - assets/share.png
    - assets/play.png
    - assets/trophy.png
    - assets/medal.png
    - assets/cardbg.png
    - assets/play.png
    - assets/search.png
    - assets/steps.png
    - assets/winner.png
    - assets/route.png
    - assets/line.png
    - assets/graph.png
    - assets/route_map.png
    - assets/running.png
    - assets/cycling-track.png
    - assets/progressbar.png
    - assets/duel_graph.png
    - assets/progressbar_pink.png
    - assets/farrah.png
    - assets/alex.png
    - assets/upload.png
    - assets/steps_pink.png
    - assets/energy.png
    - assets/profile.png
    - assets/workout.png
    - assets/goal.png
    - assets/longest.png
    - assets/move.png
    - assets/blackheart.png
    - assets/gradient_cycling.png
    - assets/location_icon.png
    - assets/notification_icons.png
    - assets/close_friends_icons.png
    - assets/sound_icon.png
    - assets/privacy_icon.png
    - assets/edit.png
    - assets/friends.png
    - assets/ellipse.png
    - assets/body.png
    - assets/goals.png
    - assets/settings.png
    - assets/more_pink.png
    - assets/back_pink.png
    - assets/chat.png
    - assets/heart.png



   
  fonts:
    - family: CircularStd
      fonts:
        - asset: fonts/CircularStd.ttf